
set(target ${CMAKE_PROJECT_NAME})
set(include_directories "")
set(dependencies "")

set(GOLXZNR_PACKAGE_NAME GolxznRender)
set(GOLXZNR_INCLUDE_DIR ${root}/code/include)
set(GOLXZNR_SOURCES_DIR ${root}/code/src)
set(GOLXZNR_TESTS_DIR ${root}/tests)
set(GOLXZNR_EXAMPLES_DIR ${root}/examples)
set(GOLXZNR_EXAMPLE_TARGET opengl_rectangle CACHE STRING "Example folder to build")
set(GOLXZNR_DEPENDENCIES_DIR ${root}/dependencies)
set(GOLXZNR_CXX_STANDARD 17)

set(GOLXZNR_GLAD_API "gl:core=3.3" CACHE STRING "GLAD API")
set(GOLXZNR_GLAD_EXTENSIONS "" CACHE STRING "GLAD extensions")
mark_as_advanced(GOLXZNR_OPENGL_PROFILE GOLXZNR_OPENGL_VERSION GOLXZN_OPENGL_EXTENSIONS)

option(GOLXZNR_BUILD_EXAMPLES "Build examples" OFF)
option(GOLXZNR_DEVELOPER_MODE "Enable developer mode" OFF)
if(GOLXZNR_DEVELOPER_MODE)
	option(BUILD_MCSS_DOCS "Build documentation using Doxygen and m.css" OFF)
	option(ENABLE_COVERAGE "Enable coverage support separate from CTest's" OFF)
endif()

message(STATUS "-- -- -- -- -- -- -- -- -- -- -- -- Variables -- -- -- -- -- -- -- -- -- -- -- -- --")
message(STATUS "Target:                         | ${target}")
message(STATUS "Package:                        | ${GOLXZNR_PACKAGE_NAME}")
message(STATUS "Root:                           | ${root}")
message(STATUS "C++ standard:                   | ${GOLXZNR_CXX_STANDARD}")
message(STATUS "Is top level:                   | ${PROJECT_IS_TOP_LEVEL}")
message(STATUS "Developer mode:                 | ${GOLXZNR_DEVELOPER_MODE}")
message(STATUS "Include directory:              | ${GOLXZNR_INCLUDE_DIR}")
message(STATUS "Sources directory:              | ${GOLXZNR_SOURCES_DIR}")
message(STATUS "Tests directory:                | ${GOLXZNR_TESTS_DIR}")
message(STATUS "Dependencies directory:         | ${GOLXZNR_CXX_STANDARD}")
message(STATUS "-- -- -- -- -- -- -- -- -- -- -- -- -- --- -- -- -- -- -- -- -- -- -- -- -- -- -- --")

